"""Assemble the attribution footer once, and strip the ones agents typed anyway.

Imported by `gh-comment` (issue and PR comments, closes, new issues) and
`gh-pr` (PR bodies). Not run.

Every body those two scripts post ends with exactly one footer,
`_<role> · [Claude Code](https://claude.ai/code)_`, and they append it.
Nothing an agent types is a footer: `attribute` removes every attribution
line already in the body before the real one goes on.

The rule used to be prose. CLAUDE.md said PR bodies and PR comments end
with a typed `_Generated by [Claude Code](...)_`, and the harness injects
its own instruction naming `🤖 Generated with [Claude Code](...)` for PR
descriptions, a line no PR in this repository can edit. A census of the
thirty squash commits on `main` on 2026-09-22 (issue #590) found the
CLAUDE.md footer alone on eight, the harness line alone on fifteen, both
on six, and neither on one. Two mandates and a reader picking one, or
both, is the observed failure; a third sentence about precedence would be
more of the same substrate. So the rule stops depending on a reader
(ADR-0022): whatever was typed comes off, the role footer goes on, and
what the agent typed stops mattering.

The link is identical in every shape this strips and in the one it
appends, so the BDFL wake predicate (agent-bdfl.yml, matching
`[Claude Code](https://claude.ai/code)` in a causing body) and
run-telemetry's self-wake audit keep matching what these scripts post.

`Co-Authored-By: Claude ...` is stripped too. It is the harness's commit
trailer, and it reaches PR bodies because agents paste their commit
message in; the repository squashes with PR_BODY, so a PR body is the
commit message `main` keeps, and the role footer is this shop's
attribution there (#485 item 1, the PR-body half).

Liveness: retrospect's `bypassed` count (attribution.py) names every
comment that went around gh-comment, and a PR body that reached `main`
without the role footer is visible in `git log`.
"""

import re

FOOTER = "\n\n---\n_{role} · [Claude Code](https://claude.ai/code)_"

# A line that is nothing but an attribution: optional decoration (`_`,
# an emoji, whitespace), an optional `<role> · ` or `Generated by|with `,
# the Claude Code link at either URL, optional decoration. `[\W_]` rather
# than `\W` because `_` is a word character and the house footer is
# wrapped in it.
ATTRIBUTION = re.compile(
    r"^[\W_]*(?:[\w-]+ · |Generated (?:by|with) )?"
    r"\[Claude Code\]\(https://claude\.(?:ai/code|com/claude-code)\)[\W_]*$"
)
CO_AUTHOR = re.compile(r"^Co-Authored-By: Claude\b", re.I)
RULE = re.compile(r"^-{3,}$")


def typed(line):
    """True for a line that is an attribution an agent typed."""
    line = line.strip()
    return ATTRIBUTION.match(line) is not None or CO_AUTHOR.match(line) is not None


def strip(body):
    """The body without typed attribution lines, and how many came off.

    Blank lines and horizontal rules left dangling at the end go with
    them: the footer this shop appends brings its own rule, and a typed
    footer is preceded by one.
    """
    lines = body.splitlines()
    kept = [line for line in lines if not typed(line)]
    removed = len(lines) - len(kept)
    while kept and (not kept[-1].strip() or RULE.match(kept[-1].strip())):
        kept.pop()
    return "\n".join(kept).strip(), removed


def attribute(body, role):
    """The body with exactly one footer, the role's, and how many typed ones came off."""
    body, removed = strip(body)
    return body + FOOTER.format(role=role), removed
