// The footer predicate is one regex family and a trailing-rule sweep, and a
// matcher's contract only exists as its cases. These pin what comes off a
// body (issue #590's census shapes: the house footer, the harness line, both
// at once, a hand-typed role footer, a pasted commit trailer) and what must
// not (the link inside prose, a section rule mid-body).
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { test } from "node:test";

const scriptsDir = new URL(".", import.meta.url).pathname;

const driver = `
import json, sys
sys.path.insert(0, sys.argv[1])
import footer
body, removed = footer.attribute(sys.argv[2], "bdfl")
print(json.dumps({"body": body, "removed": removed}))
`;

function attribute(body) {
  const result = spawnSync("python3", ["-c", driver, scriptsDir, body], { encoding: "utf8" });
  assert.equal(result.status, 0, result.stderr);
  return JSON.parse(result.stdout);
}

const ROLE_FOOTER = "\n\n---\n_bdfl · [Claude Code](https://claude.ai/code)_";
const HOUSE = "---\n_Generated by [Claude Code](https://claude.ai/code)_";
const HARNESS = "🤖 Generated with [Claude Code](https://claude.com/claude-code)";

test("a body with no footer gains exactly the role footer", () => {
  const out = attribute("Shipped #42.\nNext: verify.");
  assert.equal(out.body, "Shipped #42.\nNext: verify." + ROLE_FOOTER);
  assert.equal(out.removed, 0);
});

test("the house footer CLAUDE.md used to prescribe comes off, rule included", () => {
  const out = attribute(`Shipped #42.\n\n${HOUSE}`);
  assert.equal(out.body, "Shipped #42." + ROLE_FOOTER);
  assert.equal(out.removed, 1);
});

test("the harness's own attribution line comes off", () => {
  const out = attribute(`Shipped #42.\n\n${HARNESS}\n`);
  assert.equal(out.body, "Shipped #42." + ROLE_FOOTER);
  assert.equal(out.removed, 1);
});

test("both at once, the shape six of thirty squash commits carried, leaves one footer", () => {
  const out = attribute(`Shipped #42.\n\n${HOUSE}\n\n${HARNESS}`);
  assert.equal(out.body, "Shipped #42." + ROLE_FOOTER);
  assert.equal(out.removed, 2);
  assert.equal(out.body.split("[Claude Code]").length - 1, 1);
});

test("a role footer typed by hand is replaced, not doubled", () => {
  const out = attribute("Shipped #42.\n\n---\n_reviewer · [Claude Code](https://claude.ai/code)_");
  assert.equal(out.body, "Shipped #42." + ROLE_FOOTER);
  assert.equal(out.removed, 1);
});

test("a pasted commit trailer comes off: the squash makes the PR body the commit", () => {
  const out = attribute("Shipped #42.\n\nCo-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>");
  assert.equal(out.body, "Shipped #42." + ROLE_FOOTER);
  assert.equal(out.removed, 1);
});

test("the link inside a sentence is content and stays", () => {
  const body = "Docs point at [Claude Code](https://claude.ai/code) for the harness.";
  const out = attribute(body);
  assert.equal(out.body, body + ROLE_FOOTER);
  assert.equal(out.removed, 0);
});

test("a section rule mid-body survives; only the trailing one goes", () => {
  const out = attribute(`## Symptom\n\nx\n\n---\n\n## Fix\n\ny\n\n---\n${HARNESS}`);
  assert.equal(out.body, "## Symptom\n\nx\n\n---\n\n## Fix\n\ny" + ROLE_FOOTER);
  assert.equal(out.removed, 1);
});
