// gh-pr assembles two things agents kept getting wrong by hand: the credential
// a PR must ride (issue #489: the workflow token's PR is born with no checks;
// issue #141: the PAT's PR wakes the BDFL on itself) and the footer (issue
// #590: three sources described it, a quarter of merged bodies followed any).
// Both are argv- and env-shaped, so a stub `gh` on PATH is the whole harness.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { chmodSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

const script = join(new URL(".", import.meta.url).pathname, "gh-pr");

function run(args, { body = "Shipped #42.", env = {} } = {}) {
  const stub = mkdtempSync(join(tmpdir(), "gh-pr-"));
  const log = join(stub, "argv.json");
  const recorder = join(stub, "record.mjs");
  writeFileSync(
    recorder,
    `import { writeFileSync } from "node:fs";
const argv = process.argv.slice(2);
if (argv[0] === "auth") { console.log("app-token-from-gh-auth"); process.exit(0); }
writeFileSync(${JSON.stringify(log)}, JSON.stringify({
  argv,
  token: process.env.GH_TOKEN ?? null,
  admin: process.env.GH_ADMIN_TOKEN ?? null,
}));
console.log("https://github.com/o/r/pull/7");
`,
  );
  writeFileSync(join(stub, "gh"), `#!/bin/sh\nexec node ${recorder} "$@"\n`);
  chmodSync(join(stub, "gh"), 0o755);
  const base = {
    PATH: `${stub}:${process.env.PATH}`,
    ROLE: "bdfl",
    GH_TOKEN: "app-token",
    GH_WORKFLOW_TOKEN: "workflow-token",
    GH_ADMIN_TOKEN: "admin-token",
  };
  const proc = spawnSync("python3", [script, ...args], {
    encoding: "utf8",
    input: body,
    env: Object.fromEntries(Object.entries({ ...base, ...env }).filter(([, v]) => v !== undefined)),
  });
  let called = null;
  try {
    called = JSON.parse(readFileSync(log, "utf8"));
  } catch {
    // gh never reached `pr create`; the refusal tests assert exactly that.
  }
  return { ...proc, called };
}

test("opens the PR from the named head with title, labels, one role footer, on the app token", () => {
  const { status, stdout, called } = run(["claude/bdfl-x", "footer: assemble it", "--label", "agent-system"]);
  assert.equal(status, 0);
  assert.equal(stdout.trim(), "https://github.com/o/r/pull/7");
  assert.deepEqual(called.argv.slice(0, 6), [
    "pr",
    "create",
    "--head",
    "claude/bdfl-x",
    "--title",
    "footer: assemble it",
  ]);
  assert.equal(called.argv[6], "--body");
  assert.match(called.argv[7], /^Shipped #42\.\n\n---\n_bdfl · \[Claude Code\]\(https:\/\/claude\.ai\/code\)_$/);
  assert.deepEqual(called.argv.slice(8), ["--label", "agent-system"]);
  assert.equal(called.token, "app-token");
  // The admin PAT is stripped, not merely unused: an ambient one is the bug.
  assert.equal(called.admin, null);
});

test("typed footers of every census shape come off; exactly one footer lands", () => {
  const body = "Shipped #42.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n\n"
    + "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\n"
    + "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>";
  const { status, stderr, called } = run(["claude/x", "t"], { body });
  assert.equal(status, 0);
  assert.equal(called.argv[7].split("[Claude Code]").length - 1, 1);
  assert.doesNotMatch(called.argv[7], /Co-Authored-By|Generated/);
  assert.match(stderr, /stripped 3 typed attribution line/);
});

test("with no GH_TOKEN the session's own credential comes from gh auth token", () => {
  const { status, called } = run(["claude/x", "t"], { env: { GH_TOKEN: undefined } });
  assert.equal(status, 0);
  assert.equal(called.token, "app-token-from-gh-auth");
});

test("a GH_TOKEN that is the workflow token is refused: that PR is born with no checks", () => {
  const { status, stderr, called } = run(["claude/x", "t"], { env: { GH_TOKEN: "workflow-token" } });
  assert.equal(status, 1);
  assert.equal(called, null);
  assert.match(stderr, /workflow token/);
  assert.match(stderr, /#489/);
});

test("refuses without ROLE, without a body, and with an empty title, before gh is reached", () => {
  assert.equal(run(["claude/x", "t"], { env: { ROLE: "" } }).called, null);
  assert.equal(run(["claude/x", "t"], { body: "" }).called, null);
  const empty = run(["claude/x", "  "]);
  assert.equal(empty.called, null);
  assert.match(empty.stderr, /needs a title/);
});
