import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

export const ISSUE_MARKER = "<!-- monster-ci-failure -->";
export const ISSUE_TITLE = "🐛 Monster CI failure";

const failedConclusions = new Set(["failure", "timed_out"]);

function cleanLine(line) {
  return line
    .replace(/\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])/g, "")
    .replace(/^.*?\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z(?:\s+|$)/, "")
    .replace(/^##\[error\]\s*/, "error: ")
    .replace(/^##\[warning\]\s*/, "warning: ")
    .trimEnd();
}

function useful(line) {
  return /^(?:error(?:\[[A-Z]\d+\])?:|fatal:|thread ['"].+['"] panicked|test .+ \.\.\. FAILED|failures:|Caused by:)/i
    .test(
      line.trimStart(),
    );
}

function fallback(line) {
  return /(?:Process completed with exit code|timed out|operation was canceled|No space left on device)/i.test(
    line,
  );
}

export function firstUsefulFailure(raw, conclusion = "failure") {
  const lines = raw.split(/\r?\n/).map(cleanLine);
  let index = lines.findIndex(useful);
  if (index === -1) index = lines.findIndex(fallback);
  if (index === -1) {
    return [`Job ended with ${conclusion}; no diagnostic line was available.`];
  }

  const excerpt = [];
  for (let i = index; i < lines.length && i < index + 10 && excerpt.length < 4; i += 1) {
    const line = lines[i].trimEnd();
    if (!line || /^##\[(?:group|endgroup)\]/.test(line)) continue;
    excerpt.push(line.slice(0, 500));
  }
  return excerpt;
}

export function parseLaneName(name) {
  const parts = name.split(" | ");
  if (parts.length !== 4 || parts.some((part) => !part)) return null;
  const [os, architecture, abi, toolchain] = parts;
  return { os, architecture, abi, toolchain };
}

export function failedMatrixJobs(jobs) {
  return jobs
    .filter((job) => failedConclusions.has(job.conclusion))
    .map((job) => ({ job, lane: parseLaneName(job.name) }))
    .filter(({ lane }) => lane !== null);
}

export function buildReport(jobs, logsById, runUrl) {
  const failures = failedMatrixJobs(jobs).sort((left, right) => left.job.name.localeCompare(right.job.name));

  if (failures.length === 0) {
    throw new Error("no failed monster matrix jobs found");
  }

  const lines = [
    ISSUE_MARKER,
    "The weekly/manual monster matrix failed.",
    "",
    `Run: [${runUrl}](${runUrl})`,
    "",
    "## Failed lanes",
  ];

  for (const { job, lane } of failures) {
    const excerpt = firstUsefulFailure(logsById.get(String(job.id)) ?? "", job.conclusion);
    lines.push(
      "",
      `### \`${lane.os} | ${lane.architecture} | ${lane.abi} | ${lane.toolchain}\``,
      "",
      `- Job: [${job.html_url}](${job.html_url})`,
      `- OS: \`${lane.os}\``,
      `- Architecture / ABI / toolchain: \`${lane.architecture}\` / \`${lane.abi}\` / \`${lane.toolchain}\``,
      "- First useful failure:",
      "",
      ...excerpt.map((line) => `    ${line}`),
    );
  }

  lines.push(
    "",
    "This issue is updated and reopened on later failures; reruns never create one issue per lane.",
    "",
    "---",
    `_Generated by [GitHub Actions](${runUrl})_`,
    "",
  );
  return lines.join("\n");
}

export function selectIssue(issues) {
  const candidates = issues
    .filter(
      (issue) =>
        issue?.body?.includes(ISSUE_MARKER)
        && issue?.author?.login === "github-actions[bot]",
    )
    .sort((left, right) => {
      const leftClosed = left.state === "OPEN" ? 0 : 1;
      const rightClosed = right.state === "OPEN" ? 0 : 1;
      if (leftClosed !== rightClosed) return leftClosed - rightClosed;
      return left.number - right.number;
    });

  const selected = candidates[0];
  return selected ? { number: selected.number, state: selected.state } : null;
}

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function main([command, ...args]) {
  switch (command) {
    case "title":
      process.stdout.write(`${ISSUE_TITLE}\n`);
      break;
    case "parse": {
      const [log, conclusion = "failure"] = args;
      process.stdout.write(`${JSON.stringify(firstUsefulFailure(readFileSync(log, "utf8"), conclusion))}\n`);
      break;
    }
    case "failures":
      process.stdout.write(`${failedMatrixJobs(readJson(args[0]).jobs).length}\n`);
      break;
    case "report": {
      const [jobsPath, logsDirectory, runUrl, output] = args;
      const jobs = readJson(jobsPath).jobs;
      const logs = new Map(
        jobs.map((job) => {
          const path = join(logsDirectory, `${job.id}.log`);
          try {
            return [String(job.id), readFileSync(path, "utf8")];
          } catch {
            return [String(job.id), ""];
          }
        }),
      );
      writeFileSync(output, buildReport(jobs, logs, runUrl));
      break;
    }
    case "select": {
      const selected = selectIssue(readJson(args[0]));
      process.stdout.write(`${JSON.stringify(selected)}\n`);
      break;
    }
    default:
      throw new Error(`usage: monster-report.mjs title|parse|failures|report|select, got ${command ?? "nothing"}`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  main(process.argv.slice(2));
}
