#!/usr/bin/env python3
"""Generate site/status-data.json from repository evidence.

The status page (site/status.html, issue #95) answers a visitor's three
questions: can I use this, is it any good, is it alive. Until 2026-08-28
its data file was committed and regenerated by hand, which is how the live
page came to claim 35 experiments while research/progress.jsonl held 51,
and to call benchmarks unmeasurable after the ratio gate landed. This
script replaces the hand file at deploy time, the same pattern as
run-telemetry.py and /agent-metrics.json: generated on every deploy,
never committed.

Every field names its source, and each source is parsed here and nowhere
else:

- phase, milestones      ROADMAP.md milestone headers and checkboxes
- format_version, methods  src/lib.rs (the const and the Method enum docs)
- benchmarks             bench/baseline.json (the CI ratio gate's baseline)
- experiments            research/progress.jsonl
- merged_commits_7d      git history (deploy checks out full depth)
- sloc_src, test_functions_src  the src/ tree

Self-diagnosing, per run-telemetry.py's rule that observability does not
get to break the thing it observes: a field whose source cannot be read
becomes null and a line in "problems", the page renders what exists, and
the exit code stays 0.

Usage: status-data.py <out.json>
"""

import json
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NOW = datetime.now(timezone.utc)

data = {
    "generated_at": NOW.strftime("%Y-%m-%dT%H:%M:%SZ"),
    "problems": [],
}


def field(name):
    """Run a field builder; on any failure record the problem, emit null."""

    def wrap(fn):
        try:
            value = fn()
        except Exception as err:  # noqa: BLE001 - diagnosis is the point
            data[name] = None
            data["problems"].append(f"{name}: {type(err).__name__}: {err}")
        else:
            data[name] = value
        return fn

    return wrap


@field("commit")
def _commit():
    return subprocess.run(
        ["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


@field("milestones")
def _milestones():
    """ROADMAP.md `## M<n> — Title` headers; ✅ or checkbox states below."""
    text = (ROOT / "ROADMAP.md").read_text(encoding="utf-8")
    milestones = []
    sections = re.split(r"^## (?=M\d)", text, flags=re.M)[1:]
    for section in sections:
        header, _, body = section.partition("\n")
        match = re.match(r"(M\d+)\s*[—-]+\s*(.*)", header)
        if not match:
            continue
        mid, title = match.group(1), match.group(2).strip()
        body = body.split("\n## ")[0]
        done_by_mark = "✅" in title
        title = title.replace("✅", "").strip()
        checked = len(re.findall(r"^- \[x\]", body, flags=re.M))
        unchecked = len(re.findall(r"^- \[ \]", body, flags=re.M))
        if done_by_mark or (checked and not unchecked):
            status = "done"
        elif checked:
            status = "active"
        else:
            status = "pending"
        milestones.append({"id": mid, "title": title, "status": status})
    if not milestones:
        raise ValueError("no `## M<n>` sections found in ROADMAP.md")
    return milestones


@field("phase")
def _phase():
    """Pre-alpha until every ROADMAP milestone is done (M6 is release 0.1)."""
    milestones = data.get("milestones")
    if not milestones:
        raise ValueError("phase derives from milestones, which failed")
    if all(m["status"] == "done" for m in milestones):
        return "released"
    return "pre-alpha"


@field("format_version")
def _format_version():
    text = (ROOT / "src" / "lib.rs").read_text(encoding="utf-8")
    return int(re.search(r"pub const FORMAT_VERSION: u8 = (\d+);", text)[1])


@field("methods")
def _methods():
    """Method enum variants with their doc comments, from src/lib.rs."""
    text = (ROOT / "src" / "lib.rs").read_text(encoding="utf-8")
    body = re.search(r"pub enum Method \{\n(.*?)\n\}", text, flags=re.S)[1]
    methods = []
    doc_lines = []
    for line in body.splitlines():
        line = line.strip()
        if line.startswith("///"):
            doc_lines.append(line.removeprefix("///").strip())
        elif re.match(r"\w+ = \d+,", line):
            doc = " ".join(doc_lines)
            # Strip rustdoc syntax: [`codec`] links and backticks read as
            # noise in a browser.
            doc = re.sub(r"\[`([^`]+)`\]", r"\1", doc).replace("`", "")
            doc = re.sub(r"\s*See \w+ for the payload layout\.", "", doc)
            # Doc lines wrapped mid-path leave "flag/length/ offset" after
            # the join; a slash never ends a sentence in these docs.
            doc = re.sub(r"/\s+", "/", doc)
            methods.append({"name": line.split(" ")[0], "doc": doc})
            doc_lines = []
    if not methods:
        raise ValueError("no variants parsed from enum Method")
    return methods


@field("benchmarks")
def _benchmarks():
    baseline = json.loads((ROOT / "bench" / "baseline.json").read_text())
    return {"source": "bench/baseline.json", "bits_per_byte": baseline}


@field("experiments")
def _experiments():
    entries = [
        json.loads(line)
        for line in (ROOT / "research" / "progress.jsonl")
        .read_text(encoding="utf-8")
        .splitlines()
        if line.strip()
    ]
    latest = entries[-1]
    return {
        "total": len(entries),
        "accepted": sum(e["verdict"] == "accepted" for e in entries),
        "rejected": sum(e["verdict"] == "rejected" for e in entries),
        "latest_id": latest["id"],
        "latest_hypothesis": latest["hypothesis"],
        "recent_7d": sum(
            e["date"] >= (NOW - timedelta(days=7)).strftime("%Y-%m-%d")
            for e in entries
        ),
    }


@field("merged_commits_7d")
def _merged_commits_7d():
    """Subjects matching the squash-merge convention `... (#<n>)`, so a
    direct push does not inflate the merged-PR proxy the label claims."""
    # A shallow checkout undercounts silently; refuse to publish that.
    shallow = subprocess.run(
        ["git", "-C", str(ROOT), "rev-parse", "--is-shallow-repository"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    if shallow == "true":
        raise ValueError("shallow checkout, 7-day commit count would lie")
    subjects = subprocess.run(
        ["git", "-C", str(ROOT), "log", "--since=7.days", "--pretty=%s"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    return sum(bool(re.search(r" \(#\d+\)$", s.strip())) for s in subjects)


@field("sloc_src")
def _sloc_src():
    return sum(
        len(p.read_text(encoding="utf-8").splitlines())
        for p in (ROOT / "src").rglob("*.rs")
    )


@field("test_functions_src")
def _test_functions_src():
    """Exact `#[test]` attribute lines, not substring hits in comments."""
    return sum(
        line.strip() == "#[test]"
        for p in (ROOT / "src").rglob("*.rs")
        for line in p.read_text(encoding="utf-8").splitlines()
    )


out_path = Path(sys.argv[1])
out_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
problems = data["problems"]
print(
    f"status-data: wrote {out_path} "
    f"({'clean' if not problems else f'{len(problems)} problem(s)'})"
)
for problem in problems:
    print(f"  {problem}", file=sys.stderr)
