#!/usr/bin/env python3
"""Generate site/status-data.json from repository evidence.

The status page (site/status.html, issue #95) answers a visitor's three
questions: can I use this, is it any good, is it alive. Until 2026-08-28
its data file was committed and regenerated by hand, which is how the live
page came to claim 35 experiments while research/progress.jsonl held 51,
and to call benchmarks unmeasurable after the ratio gate landed. This
script replaces the hand file at deploy time, the same pattern as
run-telemetry.py and /agent-metrics.json: generated on every deploy,
never committed.

Every field names its source, and each source is parsed here and nowhere
else:

- phase, milestones      ROADMAP.md section order and ✅ marks; item counts
                         from the GitHub Milestones the sections link
                         (`gh api` on GH_TOKEN, ADR-0047)
- format_version, methods  src/lib.rs (the const and the Method enum docs)
- benchmarks             bench/baseline.json (the CI ratio gate's baseline)
- ratio                  docs/benchmarks/*.md aggregates + baseline.json's
                         commit date (gap to the field, and when it last moved)
- experiments            research/progress.jsonl
- merged_commits_7d      git history (deploy checks out full depth)
- sloc_code_src, sloc_test_src, test_functions_src  the src/ tree
- api_surface            docs/api-surface.txt (SIMPLICITY's other half,
                         #651) + its git history for the trend

Self-diagnosing, per run-telemetry.py's rule that observability does not
get to break the thing it observes: a field whose source cannot be read
becomes null and a line in "problems", the page renders what exists, and
the exit code stays 0.

Usage: status-data.py <out.json>
"""

import json
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NOW = datetime.now(timezone.utc)

data = {
    "generated_at": NOW.strftime("%Y-%m-%dT%H:%M:%SZ"),
    "problems": [],
}


def field(name):
    """Run a field builder; on any failure record the problem, emit null."""

    def wrap(fn):
        try:
            value = fn()
        except Exception as err:  # noqa: BLE001 - diagnosis is the point
            data[name] = None
            data["problems"].append(f"{name}: {type(err).__name__}: {err}")
        else:
            data[name] = value
        return fn

    return wrap


@field("commit")
def _commit():
    return subprocess.run(
        ["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


MILESTONE_LINK = re.compile(r"https://github\.com/([\w.-]+)/([\w.-]+)/milestone/(\d+)")


def tracker_counts(owner, repo, number):
    """Open and closed item counts of one GitHub Milestone.

    `gh api`, because it is on every runner and authenticates from GH_TOKEN.
    A failure (no token, no network, no such milestone) raises with gh's
    own words, and the field wrapper turns that into a null and a problem
    line rather than a published guess.
    """
    proc = subprocess.run(
        [
            "gh", "api", f"repos/{owner}/{repo}/milestones/{number}",
            "--jq", "{open: .open_issues, closed: .closed_issues}",
        ],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise ValueError(f"milestone {number}: {proc.stderr.strip() or 'gh api failed'}")
    counts = json.loads(proc.stdout)
    return counts["open"], counts["closed"]


@field("milestones")
def _milestones():
    """ROADMAP.md `## M<n> — Title` sections in file order; state from the tracker.

    Four statuses, because three could not tell a program from unstarted
    work (operator report, 2026-09-18, #601). ADR-0047 moved item state out
    of the file: a section linking a GitHub Milestone is a deliverable and
    reads that milestone's item counts, `done` once every item is closed,
    `active` while some are, `pending` before the first. A ✅ in the title
    is a milestone delivered before the tracker held items (no retroactive
    issues), `done`. A section with neither is a program, `ongoing`. The
    link is the join key rather than the title, so a reworded header
    cannot silently turn a deliverable into a program.
    """
    text = (ROOT / "ROADMAP.md").read_text(encoding="utf-8")
    milestones = []
    sections = re.split(r"^## (?=M\d)", text, flags=re.M)[1:]
    for section in sections:
        header, _, body = section.partition("\n")
        match = re.match(r"(M\d+)\s*[—-]+\s*(.*)", header)
        if not match:
            continue
        mid, title = match.group(1), match.group(2).strip()
        body = body.split("\n## ")[0]
        link = MILESTONE_LINK.search(body)
        if "✅" in title:
            status = "done"
        elif link:
            open_items, closed_items = tracker_counts(*link.groups())
            if open_items == 0 and closed_items > 0:
                status = "done"
            elif closed_items:
                status = "active"
            else:
                status = "pending"
        else:
            status = "ongoing"
        title = title.replace("✅", "").strip()
        milestones.append({"id": mid, "title": title, "status": status})
    if not milestones:
        raise ValueError("no `## M<n>` sections found in ROADMAP.md")
    return milestones


@field("phase")
def _phase():
    """Pre-alpha until every ROADMAP milestone is done (M6 is release 0.1).

    Programs are excluded: they never reach "done", so counting them would
    pin this field to pre-alpha past 1.0 and forever after.
    """
    milestones = data.get("milestones")
    if not milestones:
        raise ValueError("phase derives from milestones, which failed")
    deliverables = [m for m in milestones if m["status"] != "ongoing"]
    if deliverables and all(m["status"] == "done" for m in deliverables):
        return "released"
    return "pre-alpha"


@field("format_version")
def _format_version():
    text = (ROOT / "src" / "lib.rs").read_text(encoding="utf-8")
    return int(re.search(r"pub const FORMAT_VERSION: u8 = (\d+);", text)[1])


@field("methods")
def _methods():
    """Method enum variants with their doc comments, from src/lib.rs."""
    text = (ROOT / "src" / "lib.rs").read_text(encoding="utf-8")
    body = re.search(r"pub enum Method \{\n(.*?)\n\}", text, flags=re.S)[1]
    methods = []
    doc_lines = []
    for line in body.splitlines():
        line = line.strip()
        if line.startswith("///"):
            doc_lines.append(line.removeprefix("///").strip())
        elif re.match(r"\w+ = \d+,", line):
            doc = " ".join(doc_lines)
            # Strip rustdoc syntax: [`codec`] links and backticks read as
            # noise in a browser.
            doc = re.sub(r"\[`([^`]+)`\]", r"\1", doc).replace("`", "")
            doc = re.sub(r"\s*See \w+ for the payload layout\.", "", doc)
            # Doc lines wrapped mid-path leave "flag/length/ offset" after
            # the join; a slash never ends a sentence in these docs.
            doc = re.sub(r"/\s+", "/", doc)
            methods.append({"name": line.split(" ")[0], "doc": doc})
            doc_lines = []
    if not methods:
        raise ValueError("no variants parsed from enum Method")
    return methods


@field("benchmarks")
def _benchmarks():
    baseline = json.loads((ROOT / "bench" / "baseline.json").read_text())
    return {"source": "bench/baseline.json", "bits_per_byte": baseline}


@field("ratio")
def _ratio():
    """The mission's number: distance to the field, and when it last moved.

    The page published eleven bits/byte figures with no target and no
    date, so a reader could not tell a codec that gained this week from
    one flat for a month, and the operator could not either (2026-09-18).
    Both halves derive from sources that already exist and are already
    guarded, so this adds no file anyone has to maintain: the gap comes
    from the generated finals reports' own aggregate row, and the date is
    the commit date of `bench/baseline.json`, which the ratio gate's
    `write` mode rewrites on an accepted ratio change and nothing else
    touches.

    Reference names are read from the report's header row rather than
    hardcoded, so a change to the pinned reference flags carries through
    instead of silently mislabeling a column.
    """
    corpora = []
    for corpus, filename in (("Canterbury", "canterbury.md"), ("Silesia", "silesia.md")):
        lines = (ROOT / "docs" / "benchmarks" / filename).read_text(
            encoding="utf-8"
        ).splitlines()

        def cells(line):
            return [c.strip().strip("*") for c in line.strip().strip("|").split("|")]

        header = cells(next(l for l in lines if l.startswith("| file |")))
        row = cells(next(l for l in lines if l.startswith("|") and "aggregate" in l))
        ours = float(row[2])
        # Columns 0-2 are file, bytes and mothergod's own b/B; every later
        # `<tool> b/B` column is a reference compressor.
        references = {
            name.removesuffix(" b/B"): float(row[i])
            for i, name in enumerate(header)
            if i > 2 and name.endswith("b/B")
        }
        if not references:
            raise ValueError(f"no reference b/B columns in {filename}")
        best = min(references, key=references.get)
        corpora.append(
            {
                "corpus": corpus,
                "source": f"docs/benchmarks/{filename}",
                "bits_per_byte": ours,
                "best_reference": best,
                "best_bits_per_byte": references[best],
                # Positive means mothergod is behind the strongest reference.
                "gap": round(ours - references[best], 6),
            }
        )

    written = subprocess.run(
        ["git", "-C", str(ROOT), "log", "-1", "--format=%cs", "--", "bench/baseline.json"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    if not written:
        raise ValueError("no commit touches bench/baseline.json")
    age = (NOW.date() - datetime.fromisoformat(written).date()).days
    return {"corpora": corpora, "baseline_written": written, "baseline_age_days": age}


@field("experiments")
def _experiments():
    entries = [
        json.loads(line)
        for line in (ROOT / "research" / "progress.jsonl")
        .read_text(encoding="utf-8")
        .splitlines()
        if line.strip()
    ]
    latest = entries[-1]
    return {
        "total": len(entries),
        "accepted": sum(e["verdict"] == "accepted" for e in entries),
        "rejected": sum(e["verdict"] == "rejected" for e in entries),
        "latest_id": latest["id"],
        "latest_hypothesis": latest["hypothesis"],
        "recent_7d": sum(
            e["date"] >= (NOW - timedelta(days=7)).strftime("%Y-%m-%d")
            for e in entries
        ),
    }


@field("merged_commits_7d")
def _merged_commits_7d():
    """Subjects matching the squash-merge convention `... (#<n>)`, so a
    direct push does not inflate the merged-PR proxy the label claims."""
    # A shallow checkout undercounts silently; refuse to publish that.
    shallow = subprocess.run(
        ["git", "-C", str(ROOT), "rev-parse", "--is-shallow-repository"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    if shallow == "true":
        raise ValueError("shallow checkout, 7-day commit count would lie")
    subjects = subprocess.run(
        ["git", "-C", str(ROOT), "log", "--since=7.days", "--pretty=%s"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    return sum(bool(re.search(r" \(#\d+\)$", s.strip())) for s in subjects)


def _split_sloc():
    """Split src/ lines into code and inline-test lines.

    A single total counted unit tests as product code, 4453 of 10564
    lines on 2026-09-01, and the operator called the published number
    misleading. Every test line in src/ lives in a `#[cfg(test)] mod`
    block, and `cargo x fmt --check` gates every merge, so the block
    reliably ends at a lone `}` on the attribute's own indentation; no
    brace counting through string literals needed. A `#[cfg(test)]` on
    anything but a `mod` counts as code, which today matches reality
    (there are none) and fails toward the smaller test number.
    """
    code = test = 0
    for p in (ROOT / "src").rglob("*.rs"):
        lines = p.read_text(encoding="utf-8").splitlines()
        i = 0
        while i < len(lines):
            line = lines[i]
            if line.strip() == "#[cfg(test)]" and i + 1 < len(lines) and re.match(
                r"\s*(pub(\([^)]*\))?\s+)?mod\s", lines[i + 1]
            ):
                close = line[: len(line) - len(line.lstrip())] + "}"
                j = i + 1
                while j < len(lines) and lines[j].rstrip() != close:
                    j += 1
                test += j - i + 1
                i = j + 1
            else:
                code += 1
                i += 1
    return code, test


@field("sloc_code_src")
def _sloc_code_src():
    return _split_sloc()[0]


@field("sloc_test_src")
def _sloc_test_src():
    return _split_sloc()[1]


@field("test_functions_src")
def _test_functions_src():
    """Exact `#[test]` attribute lines, not substring hits in comments."""
    return sum(
        line.strip() == "#[test]"
        for p in (ROOT / "src").rglob("*.rs")
        for line in p.read_text(encoding="utf-8").splitlines()
    )


@field("api_surface")
def _api_surface():
    """SIMPLICITY's other half: public items visible on docs.rs (#651).

    `cargo x doc` keeps `docs/api-surface.txt` honest against what rustdoc
    actually built (x/src/doc.rs), the same way the `ratio` field above
    trusts `bench/baseline.json`: a committed number a gate can compute
    verifies on every run, so this script only has to read it back. The
    date is the file's own git history (deploy checks out full depth), not
    a stored timestamp, so the two can never disagree; the previous
    reading is the file's content as of the commit before that, giving a
    trend once a second one exists with no separate ledger to retain.
    """
    path = ROOT / "docs" / "api-surface.txt"
    count = int(path.read_text(encoding="utf-8").strip())
    log = subprocess.run(
        ["git", "-C", str(ROOT), "log", "-2", "--format=%H %cs", "--", "docs/api-surface.txt"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip().splitlines()
    if not log:
        raise ValueError("no commit touches docs/api-surface.txt")
    _newest_sha, computed_at = log[0].split(" ", 1)
    result = {"count": count, "computed_at": computed_at}
    if len(log) > 1:
        older_sha, previous_computed_at = log[1].split(" ", 1)
        previous = subprocess.run(
            ["git", "-C", str(ROOT), "show", f"{older_sha}:docs/api-surface.txt"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        result["previous_count"] = int(previous)
        result["previous_computed_at"] = previous_computed_at
    return result


out_path = Path(sys.argv[1])
out_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
problems = data["problems"]
print(
    f"status-data: wrote {out_path} "
    f"({'clean' if not problems else f'{len(problems)} problem(s)'})"
)
for problem in problems:
    print(f"  {problem}", file=sys.stderr)
