#!/usr/bin/env python3
"""Fold a fresh 14-day GitHub traffic snapshot into the traffic ledger.

GitHub's traffic API forgets daily views and clones after 14 days; the
ledger issue labeled traffic-data is the memory (issue #417). This
script reads the prior ledger body, merges the fresh /traffic/views and
/traffic/clones payloads into its fenced JSON block, and writes the
whole replacement body.

Merge rule: newest wins per UTC day and per metric. The API reports the
current day partial, so a later snapshot's larger value for the same day
is the correction, and a day absent from the fresh window keeps its
stored value. The API pads its window with explicit zero days; they are
stored as the zeros they are.

Failure is loud by design, unlike model-intel.py's bail-to-report: the
inputs are our own repo's API and our own machinery's prior body, so an
unreadable shape means something broke, and a quiet fresh start would
silently discard the accumulated series. Exit 1 and let the red run
raise the alarm. The only silent path is an EMPTY prior body, which is
the legitimate first run.

Usage: traffic-snapshot.py <views.json> <clones.json> <prior-body> <out-body>
RUN_URL names the writing run in the body.
"""

import json
import os
import re
import sys

# gh's issue-body cap is 65536 bytes; trim the oldest days if the series
# ever reaches this, recording the horizon as trimmed_before. At ~60
# bytes a day that is years away, and self-healing beats a hard failure
# nobody hits until then.
BODY_BUDGET = 60000

FENCE = re.compile(r"```json\n(.*?)\n```", re.DOTALL)


def fail(reason):
    print(f"traffic-snapshot: {reason}", file=sys.stderr)
    sys.exit(1)


def parse_prior(body):
    """Return (days, trimmed_before) from a prior ledger body, or fresh
    state for an empty one. A non-empty body without a readable JSON
    block is a defect, not a fresh start."""
    if not body.strip():
        return {}, None
    m = FENCE.search(body)
    if not m:
        fail("prior ledger body has no ```json block; refusing to drop the series")
    try:
        state = json.loads(m.group(1))
        days = state["days"]
    except (ValueError, KeyError, TypeError) as exc:
        fail(f"prior ledger JSON unreadable ({exc}); refusing to drop the series")
    return days, state.get("trimmed_before")


def merge(days, views, clones):
    """Fold both payloads into days, newest-wins per day per metric."""
    for payload, key, count_field, uniq_field in (
        (views, "views", "views", "view_uniques"),
        (clones, "clones", "clones", "clone_uniques"),
    ):
        for bucket in payload[key]:
            day = bucket["timestamp"][:10]
            row = days.setdefault(day, {})
            row[count_field] = bucket["count"]
            row[uniq_field] = bucket["uniques"]
    return days


def render(days, trimmed_before, views, clones, run_url):
    dates = sorted(days)
    total_views = sum(r.get("views", 0) for r in days.values())
    total_clones = sum(r.get("clones", 0) for r in days.values())
    state = {"days": {d: days[d] for d in dates}}
    if trimmed_before:
        state["trimmed_before"] = trimmed_before
    day_lines = ",\n".join(
        f'    "{d}": {json.dumps(days[d], sort_keys=True)}' for d in dates
    )
    fenced = '{\n  "days": {\n' + day_lines + "\n  }"
    if trimmed_before:
        fenced += f',\n  "trimmed_before": "{trimmed_before}"'
    fenced += "\n}"
    span = f"{dates[0]} to {dates[-1]}" if dates else "empty"
    trim_note = (
        f"\nDays before {trimmed_before} were trimmed to fit the issue-body cap.\n"
        if trimmed_before
        else ""
    )
    return f"""GitHub repo traffic, accumulated. The API forgets daily views and
clones after 14 days; the weekly traffic-snapshot workflow folds each
fresh window into the JSON block below, newest data winning per day.
The machinery writes this issue; nobody edits it by hand (issue #417).
Uniques are per day and per 14-day window; they do not sum across days.
Clone rows count every git clone including this repo's own Actions
checkouts, so read them as machinery-dominated; views are the human
signal.

| last 14 days (API window) | count | uniques |
|---|---|---|
| views | {views["count"]} | {views["uniques"]} |
| clones | {clones["count"]} | {clones["uniques"]} |

Accumulated: {len(dates)} days, {span}, {total_views} views, {total_clones} clones.
{trim_note}
```json
{fenced}
```

Last written by {run_url}

---
_Generated by [Claude Code](https://claude.ai/code)_
"""


def build(prior_body, views, clones, run_url):
    """The whole pipeline, pure, for the test driver."""
    for payload, key in ((views, "views"), (clones, "clones")):
        if not isinstance(payload.get(key), list) or "count" not in payload:
            fail(f"/traffic/{key} payload shape unexpected; keys: {sorted(payload)}")
    days, trimmed_before = parse_prior(prior_body)
    days = merge(days, views, clones)
    body = render(days, trimmed_before, views, clones, run_url)
    while len(body.encode()) > BODY_BUDGET and len(days) > 1:
        oldest = min(days)
        del days[oldest]
        trimmed_before = min(days)
        body = render(days, trimmed_before, views, clones, run_url)
    return body


def main():
    views_path, clones_path, prior_path, out_path = sys.argv[1:5]
    try:
        views = json.load(open(views_path, encoding="utf-8"))
        clones = json.load(open(clones_path, encoding="utf-8"))
    except (OSError, ValueError) as exc:
        fail(f"payload unreadable ({exc})")
    try:
        prior_body = open(prior_path, encoding="utf-8").read()
    except OSError:
        prior_body = ""
    body = build(prior_body, views, clones, os.environ.get("RUN_URL", "an unrecorded run"))
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(body)


if __name__ == "__main__":
    main()
